Repository rupali-codes/LinksHub, pull requests merged in 2023-12, with the labels that each got.

#2192 Added a card in the resume builder - (Overleaf) .
  database/placement_prep/resume-building.json
Labels: status: ready-to-merge, goal: build

#2198 Added navigation for mobile devices
  assets/icons/svg/nav/search-active.svg
  assets/icons/svg/nav/search-inactive.svg
  components/MobileBottomNav/MobileBottomNav.tsx
  layouts/GeneralLayout.tsx
  pages/index.tsx
Labels: status: ready-to-merge

#2201 Added dsa 90 days roadmap link in others category
  database/other/roadmaps.json
Labels: goal: new-link, status: ready-to-merge, goal: new-category, priority: low, chore

#2208 feat: add 'IaC' sub-category with 'Terraform' content under 'devops' category
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/devops/iac.json
  database/index.ts
Labels: goal: new-feature, status: ready-to-merge, goal: new-category, priority: low, priority: high, chore

#2207 docs: updating the README and Contributing Guide
  CONTRIBUTING.md
  README.md
Labels: documentation, priority: low

#2213 feat: added firebase auth
  app/SignInWithGithub/SignInWithGithub.tsx
  app/api/auth/route.ts
  app/layout.tsx
  components/Cards/Card.tsx
  components/Cards/CardsList.tsx
  components/Searchbar/SearchbarReducer.ts
  components/SideNavbar/SideNavbarCategory.tsx
  lib/firebase-admin-config.tsx
  lib/firebase-config.tsx
  middleware.ts
  package.json
  pages/[category]/index.tsx
  pages/index.tsx
  pages/search.tsx
  pnpm-lock.yaml
  public/upvote.png
  public/upvoteFilled.png
  service-account.ts
  tsconfig.json
Labels: goal: new-feature, priority: high

#2216 chore: added new resources in Placement Preparation
  database/data.ts
  database/index.ts
  database/placement_prep/career-guidance.json
  database/placement_prep/certifications.json
  database/placement_prep/cover-letters.json
  database/placement_prep/interview-preparation.json
  database/placement_prep/job-portals.json
  database/placement_prep/resume-building.json
Labels: priority: low, chore

#2215 feat: add Docusaurus
  database/technical-writing/tools.json
Labels: goal: new-feature, goal: new-link, status: ready-to-merge, priority: low, priority: high

#2222 feat: Added mantine link in frontend category
  database/frontend/react.json
Labels: goal: new-feature, goal: new-link, goal: new-category, priority: low, priority: high, chore
