Repository rupali-codes/LinksHub, pull requests merged in 2023-08, with the labels that each got.

#1296 feat: workflow to add labels based on title and comment
  .github/labeler-config.yml
  .github/workflows/add-labels-pr.yml
Labels: goal: new-feature, chore, gssoc23, level3

#1394 Updated the youtube section
  database/youtube/data-structures.json
  database/youtube/ui-ux.json
Labels: goal: new-link, chore, gssoc23, level1

#1388 feat: Added Software Testing YouTube Videos Details in testing.json File
  database/youtube/testing.json
Labels: goal: new-link, gssoc23, level1

#1414 feat: remove redundant code and add styling
  components/ForkButton/GitHubForkButton.tsx
  components/StarButton/GitHubStarButton.tsx
Labels: chore, gssoc23, level2, goal: refactor

#1438 zuno community added
  database/other/communities.json
Labels: goal: new-link, chore, gssoc23, level1

#1449 Add react resources
  database/frontend/react.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1440 open source blog added
  database/open_source/blogs.json
Labels: goal: new-link, chore, gssoc23, level1

#1416 added AWS Amplify for database and authentication
  database/backend/authentication.json
  database/backend/database.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1417 feat: made search bar accessible 🔍✨
  components/Searchbar/Searchbar.tsx
Labels: goal: new-feature, gssoc23, level3, accessibility

#1476 chore: fix warning as per official docs
  pages/_document.tsx
Labels: bug, documentation, chore

#1480 codenewbie podcast added
  database/other/podcasts.json
Labels: goal: new-link, chore, gssoc23, level1

#1462 feat : Added devops category and links for its resources in subcategories.
  components/TopBar/CategoryDescriptions.ts
  database/DevOps/cicd.json
  database/DevOps/devopsLifecycle.json
  database/DevOps/devopsMethodologies.json
  database/DevOps/docker.json
  database/DevOps/kubernetes.json
  database/DevOps/microservices.json
  database/data.ts
  database/index.ts
  types/index.ts
Labels: goal: new-feature, goal: new-link, chore, goal: new-category

#1482 feat: implement prefers reduced motion feature to enhance accessibility 🚀✨
  styles/globals.css
Labels: goal: new-feature, accessibility

#1487 Add Official Docs for Express ✨
  database/resources/official-docs.json
Labels: goal: new-link, gssoc23, level1

#1489 [DOCS] Added a "Table on content" in the readme to make it easier to …
  README.md
Labels: documentation, gssoc23, level1

#1494 Adding Video subcategory and resource for the open source section
  database/data.ts
  database/index.ts
  database/open_source/videos.json
Labels: goal: new-link, chore, goal: new-category

#1490 maintainer updated
  data/maintainersData.ts
Labels: bug, gssoc23, level3

#1486 aws community added
  database/other/communities.json
Labels: goal: new-link, gssoc23, level1

#1475 chore: fix warnings due to styling conflicts
  components/Searchbar/Searchbar.tsx
Labels: bug, chore, gssoc23, level2

#1495 added Wes Bos youtube in webdevlepment section
  database/youtube/web-development.json
Labels: goal: new-link, gssoc23, level1

#1498 bookboon added
  database/resources/e-book.json
Labels: goal: new-link, chore, gssoc23, level1

#1507 chore: remove index.tsx and restructure
  components/BackToTop/BackToTopButton.tsx
  components/BackToTop/index.ts
  components/Cards/Card.tsx
  components/Cards/CardsList.tsx
  components/Cards/CardsListItem.tsx
  components/CopyToClipboard/CopyToClipboard.tsx
  components/CopyToClipboard/index.ts
  components/Searchbar/index.ts
  components/Share/Share.tsx
  components/Share/index.ts
  components/SideNavbar/SideNavbarBody.tsx
  components/SideNavbar/index.ts
  components/ThemeToggler/intex.ts
  components/TopBar/TopBar.tsx
  components/popup/popupInfo.tsx
  database/artificial_intelligence/data-science.json
  database/artificial_intelligence/deep-learning.json
  database/artificial_intelligence/machine-learning.json
  database/data.ts
  database/index.ts
  database/internet_of_things/coursera.json
  database/internet_of_things/raspberry.json
  layouts/GeneralLayout.tsx
  package.json
  pnpm-lock.yaml
  types/index.ts
Labels: chore

#1501 add: animate.css
  database/frontend/animations.json
Labels: goal: new-link, chore, gssoc23, level1

#1431 feat: make search bar sticky and adjust scrollable area
  components/SideNavbar/SideNavbarBody.tsx
Labels: chore, gssoc23, level2

#1466 chore: Add Icon-Icons to the frontend/icons category.
  database/frontend/icons.json
Labels: goal: new-link, chore

#1473 chore: improve codebase by updating .gitignore and issue forms
  .github/ISSUE_TEMPLATE/add_link.yml
  .gitignore
  .vscode/settings.json
Labels: bug, chore, gssoc23, level2, goal: refactor

#1472 chore: add aria label attribute to every link & button
  components/BackToTop/BackToTopButton.tsx
  components/Footer/Footer.tsx
  components/Header/Header.tsx
  components/NewIssue/NewIssue.tsx
  components/Searchbar/Searchbar.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarElement.tsx
  components/SideNavbar/SideNavbarHeader.tsx
  components/ThemeToggler/themeToggler.tsx
  pages/contributors.tsx
  pages/index.tsx
Labels: chore, gssoc23, level2, accessibility

#1493 Spellcheck
  .github/workflows/spellcheck.yml
Labels: goal: new-feature, gssoc23, level3, collab

#1512 feat: Update CONTRIBUTING.md ✨
  CONTRIBUTING.md
Labels: goal: new-feature

#1425 fix: improve sidenavbar body with opacity
  components/SideNavbar/SideNavbarBody.tsx
Labels: chore, gssoc23, level2, goal: refactor

#1514 fix: terminal warnings and remove unnecessary code
  components/Searchbar/Searchbar.tsx
  components/Share/Share.tsx
Labels: bug, chore, gssoc23, level2

#1485 chore: add close button on popup
  components/popup/popupInfo.tsx
Labels: bug, gssoc23, level2

#1423 Refactor: Search.tsx ✨
  pages/search.tsx
Labels: chore, gssoc23, level2, goal: refactor

#1541 bookyard added
  database/resources/e-book.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1520 Added dsa video
  database/youtube/data-structures.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1542 the coder coder added
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1528 feat: add official docs of Ember.js⚡
  database/resources/official-docs.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1521 chore: add competitive programming category
  database/competitive_programming/platforms.json
  database/data.ts
  database/frontend/online-code-editors.json
  database/index.ts
  types/index.ts
Labels: chore, status: ready-to-merge, goal: new-category

#1532 feat: add official docs of Laravel ✨
  database/resources/official-docs.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1538 Adding Stackoverflow Poadcast
  database/other/podcasts.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1471 fix bug: text overlap in search result
  components/Header/Header.tsx
  components/TopBar/TopBar.tsx
  hooks/ResultsContext.tsx
  pages/[subcategory]/index.tsx
  pages/_app.tsx
  pages/search.tsx
Labels: bug, good first issue, gssoc23, status: ready-to-merge, level2

#1533 microsoft certified added
  database/cloud_computing_platforms/azure.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1539 Fix Express.js url
  database/resources/official-docs.json
Labels: bug

#1535 dsa resources
  database/youtube/data-structures.json
Labels: goal: new-link, chore, gssoc23, level1

#1543 level up tuts added
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1554 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, chore, gssoc23, level1

#1553 Update README.md
  README.md
Labels: documentation, chore, gssoc23, level1

#1544 Add The Noun Project
  database/frontend/icons.json
Labels: goal: new-link, chore, gssoc23, level1

#1559 vmware added
  database/other/communities.json
Labels: goal: new-link, chore, gssoc23, level1

#1571 vector stock added
  database/frontend/images.json
Labels: goal: new-link, chore, gssoc23, level1

#1572 Add Adobe Fonts
  database/frontend/fonts.json
Labels: goal: new-link, chore, gssoc23, level1

#1561 devtip added
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1536 added docker resources
  database/DevOps/docker.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#1546 Add Oracle University
  database/cloud_computing_platforms/oracle.json
Labels: goal: new-link, chore, gssoc23, level1

#1550 Issue/Link template updated
  .github/ISSUE_TEMPLATE/add_link.yml
Labels: bug, chore, gssoc23, level1

#1551 Coding Ninja & Geek for Geeks Coding platofrm Added
  database/competitive_programming/platforms.json
Labels: goal: new-link, chore, gssoc23, level1

#1552 The Competitive programming dropdown fixed
  database/data.ts
  types/index.ts
Labels: bug, chore, gssoc23, level2

#1555 Update SECURITY.md
  SECURITY.md
Labels: documentation, chore, gssoc23, level1

#1398 Fix bugs and refactor `Searchbar` and `SideNavbar`
  components/ErrorMessage/index.tsx
  components/Searchbar/Searchbar.tsx
  components/Searchbar/SearchbarReducer.ts
  components/Searchbar/SearchbarSuggestions.tsx
  components/SideNavbar/SideNavbarBody.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  database/resources/official-docs.json
  hooks/useFilterSearch.ts
  hooks/useSearch.ts
  hooks/useSearchReducer.ts
  hooks/useSidebarSearch.ts
  package.json
  pages/search.tsx
Labels: bug, goal: refactor

#1556 joseph smith added
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1557 jdoodle added
  database/frontend/online-code-editors.json
Labels: goal: new-link, gssoc23, level1

#1558 feat: implement adaptive day/night browser bar theme 🚀🔥
  components/Header/Header.tsx
  components/ThemeToggler/themeToggler.tsx
  package.json
  pages/[subcategory]/index.tsx
  pages/index.tsx
  pages/search.tsx
  pnpm-lock.yaml
Labels: goal: new-feature, chore, gssoc23, level3

#1574 feat: Added GraphQL in backend database Category
  database/backend/database.json
Labels: goal: new-link, chore, gssoc23, level1, goal: new-category

#1575 fix: revise commit section in contributing guide
  CONTRIBUTING.md
Labels: bug, documentation, chore

#1578 SPOJ ADDED
  database/competitive_programming/platforms.json
Labels: goal: new-link, chore, gssoc23, level1

#1581 codeforces added
  database/competitive_programming/platforms.json
Labels: goal: new-link, chore, gssoc23, level1

#1582 ideone added
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1588 neso academy added
  database/youtube/computer-science.json
Labels: goal: new-link, chore, gssoc23, level1

#1587 cs academy added
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1580 atcoder added
  database/competitive_programming/platforms.json
Labels: goal: new-link, chore, gssoc23, level1

#1586 rextester added
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1577 coding blocks added
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc, level1

#1579 feat: Added Python Official Docs Details in resources Section
  database/resources/official-docs.json
Labels: goal: new-link, chore, status: ready-to-merge

#1589 Add FreeImages
  database/frontend/images.json
Labels: goal: new-link, chore, status: ready-to-merge

#1611 New golang tutorial added by freecodecamp.org
  database/languages/golang.json
Labels: goal: new-link, chore

#1603 feat: added automation for drafting a release
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: goal: new-feature

#1604 [Added] codespaces auto setup
  .devcontainer/devcontainer.json
Labels: goal: new-feature, chore, level3

#1609 Fix database config
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/youtube/software-testing.json
  types/index.ts
Labels: bug

#1591 Added json data in backend/caching.json
  database/backend/caching.json
Labels: goal: new-link, chore

#1614 chore: add fontmirror to frontend/fonts category #1598
  database/frontend/fonts.json
Labels: chore, goal: new-category

#1597 feat: add section about our participation in open source outreach programs
  README.md
  public/gssoc-logo.png
Labels: documentation, chore, level1

#1621 Added description for programming languages:
  components/TopBar/CategoryDescriptions.ts
Labels: chore

#1628 fix: exact match for subcategory
  hooks/useFilterDB.ts
Labels: bug, chore, goal: new-category

#1629 fix: OTHER-category at the end
  database/data.ts
Labels: bug, chore, goal: new-category

#1622 chore: update description of golang resource by programiz
  database/languages/golang.json
Labels: chore

#1599 Fix SSG not generating the actual page content on initial load
  components/Loader/Preloader.tsx
  database/data.ts
  hooks/useFilterDB.ts
  hooks/useLoader.ts
  pages/[subcategory]/index.tsx
  pages/index.tsx
  types/index.ts
Labels: bug, chore

#1634 Fix/searchbar accessibility
  components/Searchbar/Searchbar.tsx
Labels: bug, accessibility

#1633 chore:add-Picular-site-in-color-section
  database/frontend/colors.json
Labels: goal: new-link, chore

#1638 feat: add Anmol to maintainer list
  data/maintainersData.ts
Labels: goal: new-feature, chore

#1640 fix: replaced with correct URL
  database/youtube/software-testing.json
Labels: bug

#1635 feat: make screen non-scrollable in mobile view when sidebar is open
  layouts/GeneralLayout.tsx
Labels: bug, chore
