Repository rupali-codes/LinksHub, pull requests merged in 2023-06, with the labels that each got.

#827 Adding LinksHub landing page style guide
  product-design/Style guide/LinksHub Styleguide.png
Labels: enhancement

#749 chore: added blog -Resolving merge conflict on Github in category,subcategory
  database/opensource/blogs.json
Labels: chore, gssoc23, level1

#840 Android development playlist link added
  database/youtube/android.json
Labels: chore, gssoc23, level1

#849 Add Firebase Database
  database/backend/database.json
Labels: chore, gssoc23, status: ready-to-merge, level1

#851 Chore: Add Khroma link to colors subcategory
  database/frontend/colors.json
Labels: goal: new-link, chore

#852 chore: Add CSS Grid Generator
  database/frontend/ui-generators.json
Labels: goal: new-link, chore, status: ready-to-merge

#858 chore: added SmallDevTools
  database/other/devtools.json
Labels: goal: new-link, chore

#861 Added new resource DSA playlist
  database/youtube/data-structures.json
Labels: goal: new-link, gssoc23, level1

#854 fix: overflowing content bug
  components/Cards/Card.tsx
Labels: bug, gssoc23, level3

#886 Add Tigris as one of open source databases
  database/backend/database.json
Labels: goal: new-link, chore

#878 feat: add ruby subcategory under languages
  database/data.ts
  database/index.ts
  database/languages/ruby.json
Labels: enhancement, gssoc23, status: ready-to-merge, level1

#875 added geekrepos in open source tools
  database/opensource/tools.json
Labels: goal: new-link, gssoc23, level1

#823 Added the search button beside the SearchBar and added validation
  components/Searchbar/Searchbar.tsx
Labels: enhancement, gssoc23, level3

#563 chore: added Fontesk to frontend database under subcategory fonts
  database/frontend/fonts.json
Labels: goal: new-link, chore, gssoc23, level1

#806 [fix] add article on how to solve merge conflicts
  CONTRIBUTING.md
Labels: documentation, enhancement, good first issue, chore

#877 chore: add AI Colors under the frontend/colors subcategory
  database/frontend/colors.json
Labels: chore, gssoc23, level1

#884 Added new blog for react
  database/resources/blogs.json
Labels: chore, gssoc23, level1

#887 Added the blog related to issue-881
  database/resources/blogs.json
Labels: chore, gssoc23, status: ready-to-merge, level1

#891 chore: added Devhints
  database/other/devtools.json
Labels: goal: new-link, chore

#900 fix: delay in color change in scrollbar #252
  components/SideNavbar/SideNavbarBody.tsx
Labels: bug, enhancement, good first issue, frontend, status: ready-to-merge

#893 chore: Add Icon Finder
  database/frontend/icons.json
Labels: goal: new-link, chore

#909 FIX : OnlineGDB link
  database/frontend/online-code-editors.json
Labels: chore, gssoc23, level1

#933 ADD : Custom Scrollbar
  styles/globals.css
Labels: enhancement, frontend, gssoc23, level2

#921 Typo error for uiverse card
  database/frontend/ui-generators.json
Labels: bug, gssoc23, level1

#857 Add Hello World DSA
  database/youtube/data-structures.json
Labels: chore, gssoc23, status: ready-to-merge, level1

#892 update: typo for greetings.yml workflow script
  .github/workflows/greetings.yml
Labels: bug, gssoc23, level1

#913 feat: add C Programming subcategory in Languages
  database/data.ts
  database/index.ts
  database/languages/c-programming.json
Labels: gssoc23, status: ready-to-merge, level1, goal: new-category

#916 chore: add Awesome Illustrations 4 Projects in frontend/illustrations
  database/frontend/illustrations.json
Labels: goal: new-link, gssoc23, status: ready-to-merge, level1

#925 chore: Add daily.dev
  database/resources/blogs.json
Labels: goal: new-link, gssoc23, level1

#926 Added Cloud Computing projects related to issue-923
  database/resources/project-ideas.json
Labels: goal: new-link, chore, gssoc23, level1

#934 Add One Page Love to design inspiration subcategory
  database/frontend/colors.json
  database/frontend/design-inspirations.json
Labels: goal: new-link, chore

#649 chore: added multiple links
  database/frontend/online-code-editors.json
  database/frontend/react.json
  database/languages/csharp.json
  database/languages/golang.json
  database/languages/javascript.json
  database/languages/python.json
  database/opensource/projects.json
  database/resources/blogs.json
  database/resources/hosting.json
  database/resources/project-ideas.json
  database/youtube/android.json
  database/youtube/computer-science.json
Labels: goal: new-link, chore, gssoc23, level1

#912 feat: add Community subcategory in Resources
  database/data.ts
  database/index.ts
  database/other/communities.json
Labels: gssoc23, level1, goal: new-category

#915 feat: add videos subcategory in frontend
  database/data.ts
  database/frontend/videos.json
  database/index.ts
Labels: goal: new-link, gssoc23, level1, goal: new-category

#918 [ADD] <SuperDesigner.Co>
  database/frontend/ui-generators.json
Labels: goal: new-link, chore

#922 Added typescript resource for the issue 919
  database/languages/typescript.json
Labels: goal: new-link, chore

#931 [fix] Create documentation.yml
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: enhancement

#951 chore: add developer roadmaps to other/other-resources
  database/other/other-resources.json
Labels: goal: new-link

#959 docs: update docs issue form with correct links
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: documentation, gssoc23, level2

#945 Added new youtube playlist
  database/youtube/tensorflow.json
Labels: goal: new-link, gssoc23, level1

#898 chore: wrapped Aside component with nav
  layouts/GeneralLayout.tsx
Labels: goal: new-feature, gssoc23, level1

#914 feat: add Game Development subcategory under YouTube
  database/data.ts
  database/index.ts
  database/youtube/game-development.json
Labels: gssoc23, level1, goal: new-category

#947 added codewars
  database/frontend/online-code-editors.json
Labels: goal: new-link, gssoc23, level1

#949 ADD : stackedit.io under online editors
  database/frontend/online-code-editors.json
Labels: goal: new-link, gssoc23, level1

#952 chore: add 3dicons resource ✨
  database/frontend/icons.json
Labels: goal: new-link, gssoc23, level1

#968 Removed multiple resource of react
  database/frontend/react.json
Labels: chore, gssoc23, level1

#750 chore: added smooth transition for sidebar accordion
  components/SideNavbar/SideNavbarCategory.tsx
Labels: good first issue, frontend, gssoc23, level2

#865 [fix] Revised CODEOWNERS file
  .github/CODEOWNERS
Labels: goal: new-feature, status: ready-to-merge

#953 feat: add github fork button
  components/ForkButton/GitHubForkButton.tsx
  components/SocialMedia/SocialMediaIconsList.tsx
Labels: goal: new-feature, gssoc23, level3

#826 Added official documentation to resource section
  database/data.ts
  database/index.ts
  database/resources/official-docs.json
  types/index.ts
Labels: gssoc23, level1

#973 chore: Add New Resources
  database/backend/database.json
  database/frontend/animations.json
  database/frontend/fonts.json
  database/frontend/icons.json
  database/frontend/images.json
  database/resources/blogs.json
  database/youtube/web-development.json
  database/youtube/web3-metaverse.json
Labels: goal: new-link, chore

#974 Add : New resource in Icon subcategory
  database/frontend/icons.json
Labels: gssoc23, level1

#977 Added Glassmorphism CSS Generator
  database/frontend/ui-generators.json
Labels: goal: new-link

#995 Chore: Added Frontend Mentor
  database/frontend/ui-generators.json
Labels: goal: new-link

#997 Homepage Paragraph Alignment Correction
  styles/globals.css
Labels: chore, gssoc23, level2

#998 added Django Forbid
  database/backend/security.json
Labels: goal: new-link, gssoc23, level1

#1006 Changed readme
  README.md
Labels: gssoc23, status: ready-to-merge, level1

#1011 Add an Animation Resource
  database/frontend/animations.json
Labels: goal: new-link, gssoc23, level1

#1018 chore: add colorclaim resource
  database/frontend/colors.json
Labels: goal: new-link, gssoc23, level1

#1013 Add : Illustration resource
  database/frontend/illustrations.json
Labels: chore, gssoc23, level1

#1019 feat: add meta tags for SEO and social media optimization
  pages/_document.tsx
Labels: chore, gssoc23, level2

#965 Add Befonts to the font category
  database/frontend/fonts.json
Labels: goal: new-link, chore

#948 Added the Blockchain Projects related to issue-935
  database/resources/project-ideas.json
Labels: goal: new-link, gssoc23, level1

#1012 chore: fix typos
  CONTRIBUTING.md
  README.md
  database/backend/architecture.json
  database/backend/authentication.json
  database/backend/caching.json
  database/backend/database.json
  database/backend/security.json
  database/backend/system-design.json
  database/backend/testing.json
  database/backend/validation.json
  database/frontend/accessibility.json
  database/frontend/animations.json
  database/frontend/colors.json
  database/frontend/design-inspirations.json
  database/frontend/fonts.json
  database/frontend/icons.json
  database/frontend/illustrations.json
  database/frontend/images.json
  database/frontend/online-code-editors.json
  database/frontend/react.json
  database/frontend/themes-templates.json
  database/frontend/ui-generators.json
  database/frontend/videos.json
  database/other/devtools.json
Labels: documentation, gssoc23, level1

#1026 feat: added git star button
  components/SocialMedia/SocialMediaIconsList.tsx
  components/StarButton/GitHubStarButton.tsx
Labels: goal: new-feature, frontend, gssoc23, level2

#1071 docs: add refactor issue form
  .github/ISSUE_TEMPLATE/refactor_code.yml
Labels: documentation, goal: new-feature, gssoc23, level2

#1023 docs: add workflow to lock issue conversations
  .github/workflows/lock-issue.yml
Labels: goal: new-feature, chore, gssoc23, level3

#1052 Add java in subcategory of Languages
  database/data.ts
  database/index.ts
  database/languages/java.json
  types/index.ts
Labels: goal: new-link, gssoc23, level1

#987 Chore: added subcategory events under resource
  database/data.ts
  database/index.ts
  database/opensource/opensource_blogs.json
  database/other/events.json
Labels: goal: new-link, gssoc23, level1

#1046 Fix bug: display log messages on browser's console
  components/SideNavbar/SideNavbarCategoryList.tsx
Labels: bug, gssoc23, level1

#1020 Added new python resource (Real Python)
  database/languages/python.json
Labels: gssoc23, level1

#1058 chore: add color resource ✨
  database/frontend/colors.json
Labels: goal: new-link, gssoc23, level1

#1029 feat: Added a hover effect to the fork button
  components/ForkButton/GitHubForkButton.tsx
Labels: bug

#1054 Add Kotlin in subcategory of languages
  database/data.ts
  database/index.ts
  database/languages/kotlin.json
  database/youtube/android.json
  types/index.ts
Labels: chore, gssoc23, level1

#1077 Add a Color Resource
  database/frontend/colors.json
Labels: goal: new-link, chore, gssoc23, level1

#880 java resources
  database/languages/java.json
Labels: goal: new-link, gssoc23, level1

#1078 added new programs under Community sub-category
  database/other/communities.json
Labels: goal: new-link, gssoc23, level1

#1090 Added Official Docs for Django
  database/resources/official-docs.json
Labels: goal: new-link, gssoc23, level1

#1072 feat: add missing subcategories in order
  types/index.ts
Labels: bug, gssoc23, level2

#1040 docs: update dependabot workflow
  .github/dependabot.yml
Labels: gssoc23, level2

#1100 docs: update contributing guidelines
  CONTRIBUTING.md
Labels: documentation, gssoc23, level2

#1091 Added CodeQL workflow
  .github/workflows/codeql.yml
Labels: goal: new-feature, gssoc23, level2

#1101 feat: add theme styled links in the footer
  components/Footer/Footer.tsx
Labels: frontend, gssoc23, level2

#1131 chore: added resource for tailwindCSS in UI generators
  database/frontend/ui-generators.json
Labels: goal: new-link, chore, gssoc23, level1

#1092 chore: add color resource ✨
  database/frontend/colors.json
Labels: goal: new-link, gssoc23, level1

#1119 [Add] official docs for Angular
  database/resources/official-docs.json
Labels: goal: new-link, gssoc23, level1

#1143 Add support for adding subcategories description #1098
  .github/ISSUE_TEMPLATE/category_description.yml
  CONTRIBUTING.md
  README.md
Labels: gssoc23, level2

#1149 Next.js Documentation are Added Under Official Docs
  database/resources/official-docs.json
Labels: goal: new-link, chore

#1160 Added MySQL docs in database section.
  database/backend/database.json
Labels: goal: new-link, gssoc23, level1

#1155 Add Font Awesome
  database/frontend/fonts.json
Labels: goal: new-link, gssoc23, level1

#1163 refactor: backToTopButton Component
  components/BackToTop/BackToTopButton.tsx
Labels: chore, gssoc23, level3, goal: refactor

#1164 refactor: card component
  components/Cards/Card.tsx
Labels: gssoc23, level2, goal: refactor

#1165 refactor: cardList component
  components/Cards/CardsList.tsx
Labels: gssoc23, level2, goal: refactor

#1162 refactor: themeToggler and header component
  components/Header/Header.tsx
  components/ThemeToggler/themeToggler.tsx
Labels: chore, gssoc23, level3, goal: refactor

#1146 Added youtube playlist link for android development
  database/youtube/android.json
Labels: goal: new-link, gssoc23, level1

#1145 Added the CSS Scan website to the LinksHub
  database/frontend/animations.json
Labels: goal: new-link, chore, gssoc23, level1

#1144 [Feature] Search enhancement
  components/Searchbar/Searchbar.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  database/data.ts
  hooks/useFilterSearch.ts
  hooks/useSearch.ts
  hooks/useSidebarSearch.ts
  pages/search.tsx
  types/index.ts
Labels: goal: new-feature, frontend, gssoc23, level3

#1153 chore: add game design 101 in youtube/game-development
  database/youtube/game-development.json
Labels: goal: new-link, gssoc23, level1

#1170 add the new link for OneCompiler
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1169 Added PostgreSQL to backend/database by Parmesh Bhatt
  database/backend/database.json
Labels: goal: new-link, gssoc23, level1

#1195 chore : Added link for CSS Pattern Generator
  database/frontend/ui-generators.json
Labels: goal: new-link, gssoc23, level1

#1184 Vue.js Documentation are Added Under Official Docs
  database/resources/official-docs.json
Labels: goal: new-link, gssoc23, level1
