Repository rupali-codes/LinksHub, pull requests merged in 2023-11, with the labels that each got.

#2162 fix/2153 div-overlap
  pages/[category]/[...subcategory].tsx
Labels: bug, priority: medium

#2161 Fix-#2139/Searchbar-react-bug
  components/Searchbar/Searchbar.tsx
  database/data.ts
Labels: bug, priority: medium

#2167 feat: adding Aftab to Codeowners file
  .github/CODEOWNERS
Labels: goal: new-feature, priority: high

#2160 feat: Add Swift Sub Category
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/languages/swift.json
Labels: goal: new-feature, status: ready-to-merge, goal: new-category, priority: low, priority: high, chore

#2044 [ADDED]: BlockChain Category
  components/TopBar/CategoryDescriptions.ts
  database/BlockChain/ethers.json
  database/BlockChain/hardhat.json
  database/BlockChain/smart-contracts.json
  database/BlockChain/truffle.json
  database/data.ts
  database/index.ts
  types/index.ts
Labels: status: ready-to-merge, goal: new-category, priority: low, chore

#2179 chore: Add Easings in animations subcategory
  database/frontend/animations.json
Labels: status: ready-to-merge, goal: new-category, priority: low, chore

#2121 feat: add iconsax icon
  database/frontend/icons.json
Labels: goal: new-link, status: ready-to-merge, priority: low, chore

#2116 [RESOLVED]: Sidebar not scrolling upto bottom in mobile devices
  components/SideNavbar/SideNavbar.tsx
Labels: bug, status: ready-to-merge, priority: medium

#2135 Added a Podcast resources
  database/other/podcasts.json
Labels: goal: new-link, priority: low

#2180 chore: added new resources to ui-libraries
  components/TopBar/CategoryDescriptions.ts
  database/frontend/ui-libraries.json
Labels: status: ready-to-merge

#2154 Added official documents for Go programming language
  database/resources/official-docs.json
  database/youtube/web-development.json
Labels: goal: new-link, status: ready-to-merge, priority: low

#2187 Added a new project idea (Web development) in the project-ideas.json
  database/resources/project-ideas.json
Labels: goal: new-link, status: ready-to-merge, priority: low

#2186 Sidebar Redesign
  assets/icons/SearchIcon.tsx
  assets/icons/svg/angle-down.svg
  assets/icons/svg/nav/home-active.svg
  assets/icons/svg/nav/home-inactive.svg
  assets/icons/svg/nav/save-active.svg
  assets/icons/svg/nav/save-inactive.svg
  assets/icons/svg/nav/team-active.svg
  assets/icons/svg/nav/team-inactive.svg
  assets/icons/svg/question-mark.svg
  assets/icons/svg/search.svg
  components/Button/Button.tsx
  components/Button/index.ts
  components/Searchbar/Searchbar.tsx
  components/Searchbar/ShortcutKey.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/SideNavbar/SideNavbarElement.tsx
  components/Sidebar/Sidebar.tsx
  components/Sidebar/index.ts
  layouts/GeneralLayout.tsx
  next.config.js
  package.json
  pnpm-lock.yaml
  styles/globals.css
  tailwind.config.js
Labels: goal: new-design, 🚀 ready, priority: high

#2189 chore: add workflow to handle multiple issues
  .github/workflows/handle-multiple-issues.yml
Labels: priority: high, chore

#2185 Header redesign
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/---category-suggestion.yml
  .github/ISSUE_TEMPLATE/add_link.yml
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/category_description.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
  assets/icons/svg/discord.svg
  assets/icons/svg/github.svg
  assets/icons/svg/heart.svg
  assets/icons/svg/linkedin.svg
  assets/icons/svg/logo.svg
  assets/icons/svg/moon.svg
  assets/icons/svg/sun.svg
  assets/icons/svg/x.svg
  components/Header/Header.tsx
  components/SideNavbar/SideNavbar.tsx
  components/ThemeToggler/themeToggler.tsx
  components/TopBar/CategoryDescriptions.ts
  database/BlockChain/ethers.json
  database/BlockChain/hardhat.json
  database/BlockChain/smart-contracts.json
  database/BlockChain/truffle.json
  database/data.ts
  database/frontend/animations.json
  database/frontend/icons.json
  database/frontend/ui-libraries.json
  database/index.ts
  database/languages/swift.json
  database/other/podcasts.json
  pnpm-lock.yaml
  types/index.ts
Labels: goal: new-design, 🚀 ready, priority: high
