Repository rupali-codes/LinksHub, pull requests merged in 2023-05, with the labels that each got.

#556 Added two Javascript resources
  database/languages/javascript.json
Labels: add link

#601 add: animted-fluent-emojis in db
  database/frontend/icons.json
Labels: goal: new-link, gssoc23

#603 Fix: Resolved conflicts and fixed typos in illustrations subcategory
  database/frontend/illustrations.json
Labels: goal: new-link, status: ready-to-merge

#591 [fix] add a special note for GSSoC'23 contributors
  CONTRIBUTING.md
Labels: documentation

#599 [Feature] Project Ideas
  database/data.ts
  database/index.ts
  database/resources/project-ideas.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge

#592 Add new YouTube link for web development 'developedbyed'
  database/youtube/web-development.json
Labels: goal: new-link, gssoc23, status: ready-to-merge

#585 Added two opensource link
  database/opensource/opensource_blogs.json
Labels: goal: new-link, gssoc23, status: ready-to-merge

#584 Firebase-Authentication guide added to backend/authentication.json
  database/backend/authentication.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge

#572 fix : changed hover color
  components/SideNavbar/SideNavbarElement.tsx
Labels: gssoc23, status: ready-to-merge

#560 Adding direct links to dsa playlists
  database/youtube/data-structures.json
Labels: gssoc23, status: ready-to-merge

#611 #GSSoC2023 1.Added section 'ml,ai and data' and provided links for ML, Data Science and Deep Learning
  database/data.ts
  database/index.ts
  database/languages/golang.json
  database/ml&ai/datascience.json
  database/ml&ai/deeplearning.json
  database/ml&ai/ml.json
  database/resources/blogs.json
  database/youtube/machine-learning.json
  types/index.ts
Labels: enhancement, gssoc23

#579 Chore: Added web-resources-project in opensource projects
  database/Other/Github.json
  database/Other/devtools.json
  database/opensource/projects.json
Labels: goal: new-link

#617 Python programiz in Python Language
  database/languages/python.json
Labels: goal: new-link, gssoc23

#656 [Add] Kunal Kushwaha's Java Data Structures and Algorithms Course with Interview Preparation
  database/youtube/data-structures.json
Labels: goal: new-link, chore, gssoc23

#654 open source option added to issue template
  .github/ISSUE_TEMPLATE/add_link.yml
Labels: bug, gssoc23

#655 Workflow for closing old prs added
  .github/workflows/close_old_prs.yaml
Labels: enhancement, gssoc23

#685 fix: search ux improvement
  components/SideNavbar/SideNavbarBody.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/SideNavbar/SideNavbarElement.tsx
  hooks/useSidebarSearch.ts
Labels: bug, enhancement, design, ui/ux

#623 [Add] Interactive Python Tutorial Website
  database/languages/python.json
Labels: goal: new-link, chore, gssoc23

#625 chore: added dsa resource
  database/youtube/data-structures.json
Labels: goal: new-link, chore, gssoc23

#673 Chore: Added Codecademy Docs in opensource projects
  database/opensource/projects.json
Labels: goal: new-link, chore

#662 Added 'Open Source Contributions' to 'OPENSOURCE'
  database/opensource/projects.json
Labels: goal: new-link, chore, gssoc23

#653 Chore: Add Craftwork to illustrations
  database/frontend/illustrations.json
Labels: goal: new-link, chore

#652 AI color generator
  database/frontend/colors.json
Labels: goal: new-link, chore, gssoc23

#643 chore: Added Good Docs Project in opensource projects category
  database/opensource/projects.json
Labels: goal: new-link, chore, gssoc23

#633 New UI- Generator added
  database/frontend/ui-generators.json
Labels: goal: new-link, chore, gssoc23

#642 chore: added new youtube link in subcategory web-development
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23

#689 Added github action for closing old issues
  .github/workflows/close_old_issues.yaml
Labels: enhancement, gssoc23

#684 [Add] Machine Learning Course by 5 mins Engineering
  database/youtube/machine-learning.json
Labels: goal: new-link, chore, gssoc23, level 1

#690 Chore: Added Shadow Generator in ui-generator
  database/frontend/ui-generators.json
Labels: goal: new-link, chore, level 1

#702 updated blog section
  database/resources/blogs.json
Labels: goal: new-link, gssoc23, level 1

#698 chore: added Full stack JavaScript by odin project
  database/languages/javascript.json
Labels: goal: new-link, chore

#615 New Frontend Resource - CSS In JS
  database/data.ts
  database/frontend/ui-generators.json
  database/youtube/data-structures.json
Labels: goal: new-link, gssoc23, level1

#687 added competitive programming section under Youtube
  .vscode/settings.json
  database/data.ts
  database/index.ts
  database/youtube/competitive-programming.json
  tsconfig.json
Labels: goal: new-link, chore, gssoc23, level1

#692 Added TypeScript to the Language Section
  database/data.ts
  database/index.ts
  database/languages/typescript.json
Labels: goal: new-link, chore, gssoc23, level1

#693 Read more button added when text overflow on card
  components/Cards/Card.tsx
  components/Cards/CardsListItem.tsx
Labels: enhancement, good first issue, frontend, gssoc23, level2

#726 Added 2 new animation tool
  database/frontend/animations.json
Labels: goal: new-link, chore, gssoc23, level1

#701 chore: added codecrafters
  database/Other/devtools.json
Labels: goal: new-link, gssoc23, level1

#721 Add Thapa Technical Youtube link
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, level1

#718 Chore: Added CSS Playlist Link
  database/youtube/css.json
Labels: goal: new-link, chore, gssoc23, level1

#725 chore: added nextauth in authentication backend
  database/backend/authentication.json
Labels: goal: new-link, chore, gssoc23, status: ready-to-merge, level1

#704 "Added New Frontend Resource"
  database/frontend/colors.json
Labels: goal: new-link, chore, gssoc23, level1

#751 docs: update contributing guidelines
  CONTRIBUTING.md
Labels: documentation, gssoc23, level2

#695 Create CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement, chore

#668 chore: added new resource in illustrations
  database/frontend/illustrations.json
Labels: goal: new-link, gssoc23, level1

#621 Added 'Database' feature to 'BACKEND'
  database/backend/database.json
  database/data.ts
  database/index.ts
Labels: good first issue, goal: new-link, chore, gssoc23, level1

#708 chore: added four resource links
  database/data.ts
  database/index.ts
  database/other/devtools.json
  database/other/other-resources.json
  database/resources/e-book.json
Labels: goal: new-link, gssoc23, level2

#711 Added new resources in React Js ( Frontend )
  database/frontend/react.json
Labels: goal: new-link, chore, gssoc23, level1

#738 Three new links are added in open source projects file
  database/opensource/projects.json
  database/opensource/tools.json
Labels: chore, gssoc23, level1

#752 Update close_old_prs.yaml
  .github/workflows/close_old_prs.yaml
Labels: gssoc23, status: ready-to-merge, level3, collab

#759 chore: Added one link for ui generation
  database/frontend/ui-generators.json
Labels: gssoc23, level1

#763 chore: add new JavaScript resources
  database/resources/blogs.json
Labels: gssoc23, level1

#766 chore: add Deepsource under Other in devtools
  database/other/devtools.json
Labels: gssoc23, level1

#767 chore: Add GetIllustrations in frontend category
  database/frontend/illustrations.json
Labels: gssoc23, level1

#760 [fix] Create issue template for proposing new categories
  .github/ISSUE_TEMPLATE/---category-suggestion.yml
Labels: enhancement, gssoc23, level2, collab

#786 chore: Add "Two Minute Papers" in ML in YouTube
  database/youtube/machine-learning.json
Labels: goal: new-link, chore

#740 chore: add React 2025
  database/frontend/react.json
Labels: gssoc23, level1

#787 Added the links in the youtube section sucessfully
  database/youtube/web-development.json
Labels: gssoc23, level1

#741 chore: add Fullstack Open
  database/frontend/react.json
Labels: gssoc23, level1

#748 Added 3 resources in 2 different categories
  database/youtube/competitive-programming.json
  database/youtube/computer-science.json
Labels: gssoc23, level1

#807 Added new open source project
  database/opensource/projects.json
Labels: gssoc23, level1

#607 Added transition property to social-links in navbar
  components/SocialMedia/SocialMediaIconsList.tsx
  components/ThemeToggler/themeToggler.tsx
Labels: frontend, chore, gssoc23, level2

#734 Chore: Add Happy Hues link to colors subcategory(Typo error fixed)
  database/frontend/colors.json
Labels: goal: new-link, chore

#742 chore: add Free React Bootcamp
  database/frontend/react.json
Labels: gssoc23, level1

#801 chore: Added Learn Js
  database/languages/javascript.json
Labels: goal: new-link, chore

#802 chore: Daniel Bourke Youtube Channel
  database/index.ts
  database/youtube/machine-learning.json
  database/youtube/tensorflow.json
Labels: goal: new-link, chore

#773 Full stack Web Development YT link added
  database/youtube/web-development.json
Labels: gssoc23, level1

#805 chore: add eloquent javascript e-book to resources
  database/resources/e-book.json
Labels: chore, gssoc23, level1

#587 Added new resource in dsa section
  database/youtube/data-structures.json
Labels: gssoc23, level1

#799 Chore: add Accessibility subcategory and resources to Frontend
  database/data.ts
  database/frontend/accessibility.json
  database/index.ts
Labels: goal: new-link, chore

#829 Update close_old_prs.yaml
  .github/workflows/close_old_prs.yaml
Labels: bug

#809 Added Fintech Section Under Youtube
  database/data.ts
  database/index.ts
  database/youtube/fintech.json
  types/index.ts
Labels: gssoc23, level1

#818 added new awesome opensource project
  database/opensource/projects.json
Labels: goal: new-link, gssoc23, level1

#828 Added Artificial Intelligence Projects related to issue-#812
  database/resources/project-ideas.json
Labels: goal: new-link, gssoc23, level1

#843 💡 [Feat]: Add aria-label for Social anchors & Some minor changes
  components/Cards/Card.tsx
  components/Footer/Footer.tsx
  components/SocialMedia/SocialMediaIconsList.tsx
Labels: enhancement, frontend, gssoc23, status: ready-to-merge, level2
