Repository rupali-codes/LinksHub, pull requests merged in 2023-07, with the labels that each got.

#1055 fix: extended gap in title and description
  components/Cards/Card.tsx
  components/popup/index.tsx
Labels: bug, gssoc23, level2

#1183 Added css filters to frontend/ui-generators
  database/data.ts
  database/frontend/ui-generators.json
Labels: goal: new-link, gssoc23, level1

#1152 feat: add contributors page
  components/Footer/Footer.tsx
  next.config.js
  pages/contributors.tsx
Labels: goal: new-feature, gssoc23, level3

#1196 Added sitemap.xml
  public/sitemap.xml
Labels: goal: new-feature, gssoc23, level3

#942 Chore: Add Muzli Colors link to colors subcategory and remove khroma file.
  database/frontend/colors.json
Labels: goal: new-link, chore

#1158 Added youtube link for web development #1128
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1173 Added Women-led-open-source sub-category
  database/index.ts
  database/opensource/projects.json
Labels: goal: new-link, chore, gssoc23, level1

#1174 Addiing gh action for spelling errors
  .github/workflows/spelling.yml
  components/Header/Header.tsx
Labels: goal: new-feature, status: ready-to-merge, collab

#1223 Added Appwrite for authentication and database
  database/backend/authentication.json
  database/backend/database.json
Labels: in progress, goal: new-link, chore, level1

#1231 Added youtube resource for android development
  database/youtube/android.json
Labels: goal: new-link, gssoc23, level1

#1214 chore : Added link for Java Projects
  database/resources/project-ideas.json
Labels: goal: new-link, chore, gssoc23, level1

#1234 Added new animation.
  database/frontend/animations.json
Labels: goal: new-link, chore, gssoc23, level1

#1003 Added a new resource for the C Programming language
  database/languages/c-programming.json
  pnpm-lock.yaml
Labels: gssoc23, level1

#1235 Add nuxt Documentation to Official Docs in Resources 📃
  database/resources/official-docs.json
Labels: goal: new-link, chore, gssoc23, level1

#1243 Added youtube resource for game development
  database/youtube/game-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1253 Add Shutterstock
  database/frontend/images.json
Labels: goal: new-link, gssoc23, level1

#1249 chore: Add DaFont to frontend/font category
  database/frontend/fonts.json
Labels: goal: new-link, gssoc23, level1

#1247 Added : AI Course by Prof. Mausam from IIT Delhi
  database/data.ts
  database/index.ts
  database/ml&ai/ai.json
Labels: goal: new-link, chore

#1248 refactor: useSidebarSearch component
  hooks/useSidebarSearch.ts
Labels: gssoc23, level2, goal: refactor

#1251 Added youtube resource for android development
  database/youtube/android.json
Labels: goal: new-link, gssoc23, level1

#1244 [DOCS] Add gssoc'23 timeline and pointer system
  README.md
Labels: documentation, gssoc23, level1

#1116 Added the YouTube resources for react.js by Parmesh Bhatt
  database/frontend/react.json
Labels: goal: new-link, chore, gssoc23, level1

#1258 Chore:Update ui-generators.json
  database/frontend/ui-generators.json
Labels: goal: new-link, chore, gssoc23, level1

#1269 Add Paletton to Colors
  database/frontend/colors.json
Labels: goal: new-link, chore, status: ready-to-merge

#1282 fix bug: search query overlaps search result
  components/Header/Header.tsx
  components/TopBar/CategoryDescriptions.ts
  components/TopBar/TopBar.tsx
  components/TopBar/index.ts
  pages/[subcategory]/index.tsx
  pages/search.tsx
Labels: bug

#1257 feat: add suggestions to search bar
  .github/workflows/close_old_issues.yaml
  .github/workflows/close_old_prs.yaml
  components/Searchbar/Searchbar.tsx
  package.json
  pnpm-lock.yaml
  types/index.ts
Labels: goal: new-feature

#1288 Beautify contributors page
  pages/contributors.tsx
Labels: design, chore, gssoc23, level2

#1291 added game dev link
  database/youtube/game-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1298 Added the Django Projects related to issue-1182
  database/resources/project-ideas.json
Labels: goal: new-link, chore, gssoc23, level1

#1318 refactor: remove index.ts and fix warning
  components/TopBar/TopBar.tsx
  components/TopBar/index.ts
Labels: gssoc23, level2, goal: refactor

#1319 refactor: fix warnings and add type safety
  components/SideNavbar/SideNavbarHeader.tsx
Labels: gssoc23, level2, goal: refactor

#1320 fix: warnings and remove unnecessary code
  components/SideNavbar/SideNavbarCategoryList.tsx
Labels: chore, gssoc23, level1

#1321 fix: non-null assertion error
  components/popup/index.tsx
Labels: chore, gssoc23, level1

#1322 fix: warnings due to any (type) and empty props
  components/Aside/Aside.tsx
Labels: chore, gssoc23, level1

#1323 refactor: remove index.ts file and fix warning
  components/Footer/Footer.tsx
  components/Footer/index.ts
Labels: gssoc23, level2, goal: refactor

#1324 fix: handle assertion error
  components/Backdrop/Backdrop.tsx
Labels: chore, gssoc23, level1

#1325 refactor: use Link component and fix warnings
  components/NewIssue/NewIssue.tsx
Labels: gssoc23, level2, goal: refactor

#1328 refactor: add type notation and fix warnings
  components/SideNavbar/SideNavbar.tsx
Labels: gssoc23, level2, goal: refactor

#1327 fix: warning due to any non-nullish value
  components/SideNavbar/SideNavbarBody.tsx
Labels: chore, gssoc23, level1

#1326 fix: warning due to empty props
  components/Header/Header.tsx
Labels: chore, gssoc23, level1

#1335 Added React Routes v6 Tutorial
  database/frontend/react.json
Labels: goal: new-link, chore, gssoc23, level1

#1336 javaTpoint js tutorial is added
  database/languages/javascript.json
Labels: goal: new-link, chore, gssoc23, level1

#1338 feat: Interviewbit
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1349 Added Good First Issues Tool In The Open Source Tools Subcategory
  database/open_source/tools.json
Labels: goal: new-link, chore, gssoc23, level1

#1365 updated dsa section
  database/youtube/data-structures.json
Labels: goal: new-link, chore, gssoc23, level1

#1353 Add Passportjs
  database/backend/authentication.json
Labels: goal: new-link, chore, gssoc23, level1

#1369 feat: Node.js Official Dev Doc
  database/resources/official-docs.json
Labels: goal: new-link, chore, gssoc23, level1

#1254 Feat: Add dockerized linkshub
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
Labels: goal: new-feature

#1301 feat: show maintainers/contributors state in contributors section
  data/maintainersData.ts
  pages/contributors.tsx
  styles/globals.css
Labels: frontend, chore, gssoc23, level3

#1352 revamp: hover states of social icons ✨
  components/SocialMedia/SocialMediaIconsList.tsx
  tailwind.config.js
Labels: chore, gssoc23, level2, goal: refactor

#1380 Add DevHints.io React.js cheatsheet to the Frontend/React category.
  database/frontend/react.json
Labels: goal: new-link, chore

#1290 added resource for web3-metaverse under Youtube
  database/youtube/web3-metaverse.json
Labels: goal: new-link, chore, gssoc23, level1

#1294 Added description in i button.
  components/TopBar/CategoryDescriptions.ts
Labels: chore, gssoc23, level2

#1363 feat: add official docs of tailwindcss ⚡
  database/resources/official-docs.json
Labels: goal: new-link, chore, gssoc23, level1

#1264 Feat: Sync overlay transition with sidebar transition in mobile view
  components/Backdrop/Backdrop.tsx
  components/SideNavbar/SideNavbar.tsx
Labels: bug, frontend, chore, gssoc23, level3

#1373 Created Dart Subcategory in The Languages Category
  database/data.ts
  database/index.ts
  database/languages/dart.json
Labels: goal: new-link, chore, gssoc23, level1

#1366 IOT
  components/Searchbar/Searchbar.tsx
  database/IOT/coursera.json
  database/data.ts
  database/index.ts
  types/index.ts
Labels: goal: new-link, chore, goal: new-category

#1402 Adding Kaggle site.
  database/machine_learning/data-science.json
Labels: goal: new-link, chore, gssoc23, level1

#1399 React resources
  database/frontend/react.json
Labels: goal: new-link, chore, gssoc23, level1

#1393 Svelte Documentation are Added Under Official Docs ✨
  database/resources/official-docs.json
Labels: goal: new-link, chore, gssoc23, level1

#1401 chore: Add Free3Dicon to the frontend/icons category.
  database/frontend/icons.json
Labels: goal: new-link, chore

#1400 chore: Added Game Resources
  database/youtube/game-development.json
Labels: goal: new-link, chore, gssoc23, level1

#1413 Add Dreamstime
  database/frontend/images.json
Labels: goal: new-link, chore, gssoc23, level1

#1351 chore: Added Quine Resources
  database/open_source/blogs.json
Labels: goal: new-link, chore, gssoc23, level1

#1360 Added meta tags
  pages/[subcategory]/index.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/search.tsx
Labels: goal: new-feature, chore, gssoc23, level3

#1395 gfg editor added
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1434 add: colorSpace link to frontend colors category
  database/frontend/colors.json
Labels: goal: new-link, chore, gssoc23, level1

#1437 added KNOWLEDGE GATE channel computer-science.json
  database/youtube/computer-science.json
Labels: goal: new-link, chore, gssoc23, level1

#1442 ai community added
  database/other/communities.json
Labels: goal: new-link, chore, gssoc23, level1

#1424 iot
  database/IOT/raspberry.json
  database/data.ts
  database/index.ts
Labels: goal: new-link, chore, gssoc23, level1

#1406 hovering text fixed
  components/CopyToClipboard/CopyToClipboard.tsx
  components/Share/Share.tsx
Labels: bug, chore, gssoc23, level3

#1447 feat: Added Sublime Text Online Code Editor in online-code-editors.json File in Frontend Category
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore, gssoc23, level1

#1427 docs: update contributing guidelines while adding subcategory
  CONTRIBUTING.md
Labels: documentation, chore, gssoc23, level1

#1412 feat: optimize script for google analytics with lazy loading and Script component
  pages/_document.tsx
Labels: bug, goal: new-feature, chore, gssoc23, level2

#1411 feat: disable autoComplete for searchbar
  components/Searchbar/Searchbar.tsx
Labels: goal: new-feature, gssoc23, level2

#1409 feat: add noImplicitAny & strictNullChecks in tsconfig
  tsconfig.json
Labels: goal: new-feature, chore, gssoc23, level2

#1403 cloud added
  database/cloud_computing_platforms/aws.json
  database/cloud_computing_platforms/azure.json
  database/cloud_computing_platforms/gcp.json
  database/cloud_computing_platforms/ibm.json
  database/cloud_computing_platforms/oracle.json
  database/data.ts
  database/index.ts
  types/index.ts
Labels: chore, gssoc23, level1, goal: new-category

#1389 feat: Added Web Development YouTube Video Details in web-development.json File
  database/youtube/web-development.json
Labels: goal: new-link, chore, gssoc23, level1
