Repository rupali-codes/LinksHub, pull requests merged in 2023-10, with the labels that each got.

#1707 fix: Typo Codecademy
  database/open_source/projects.json
Labels: bug

#1718 Added RazorPay api link
  database/backend/api.json
Labels: goal: new-link, chore

#1708 chore: add workflow to check spam PRs in hacktoberfest
  .github/workflows/spam_hacktoberfest.yml
Labels: chore, priority: high

#1752 Fix : selected subcategory in the sidebar
  components/SideNavbar/SideNavbarElement.tsx
Labels: bug, chore, goal: new-category

#1754 feat: Improve search bar suggestions
  components/Searchbar/Searchbar.tsx
  components/Searchbar/SearchbarSuggestions.tsx
  types/index.ts
Labels: goal: new-feature

#1756 feat: Add C# Projects in resources category
  database/resources/project-ideas.json
Labels: goal: new-feature, goal: new-link, chore

#1737 Fix searchbar query persist even after clearing the searchbar
  components/Searchbar/Searchbar.tsx
Labels: bug

#1755 feat: add Mamba UI on Ui generators
  database/frontend/ui-generators.json
Labels: goal: new-feature

#1759 fix: cpp-content
  database/languages/cpp.json
Labels: bug

#1745 chore: add option to check participation in hacktoberfest
  .github/ISSUE_TEMPLATE/---category-suggestion.yml
  .github/ISSUE_TEMPLATE/add_link.yml
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/category_description.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
Labels: priority: high

#1763 Add: Patrick Collins Yt
  database/youtube/web3-metaverse.json
Labels: goal: new-link, chore, priority: low, hacktoberfest-accepted

#1772 Fix - remove slight scroll behavior from categories page
  components/Footer/Footer.tsx
Labels: bug, hacktoberfest

#1776 adding t3 into nextjs sub category
  database/frontend/next.json
Labels: goal: new-link, chore, priority: low, hacktoberfest-accepted

#1773 add: remix icon
  database/frontend/icons.json
Labels: goal: new-link, chore, priority: low

#1787 feat: Add Unreal Sensei-Mega Tutorials Playlist in the game-development category
  database/youtube/game-development.json
Labels: goal: new-feature, chore, goal: new-category, hacktoberfest-accepted

#1789 add: Rustlings (rust)
  database/languages/rust.json
Labels: goal: new-link, chore, priority: low, hacktoberfest, hacktoberfest-accepted

#1713 Added the link to the blog to the Machine learning projects with sour…
  database/resources/blogs.json
Labels: goal: new-link, chore

#1782 Spelling, Heading, Pagination btn and URL updated
  components/Pagination/Pagination.tsx
  database/resources/official-docs.json
Labels: documentation, goal: new-link, chore, hacktoberfest-accepted

#1795 feat: added new youtube channel link(CodeNcode) in competitive programming tutorials
  database/competitive_programming/cp-tutorials.json
Labels: goal: new-feature, goal: new-link, chore, hacktoberfest-accepted

#1799 Update icons.json
  database/frontend/icons.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted

#1804 chore:Added New Link(1768)
  database/youtube/tensorflow.json
Labels: goal: new-link, chore

#1726 chore: correct the layout of description icon of subcategories for hover state
  components/TopBar/TopBar.tsx
Labels: bug

#1777 add: eva icons
  database/frontend/icons.json
Labels: hacktoberfest, hacktoberfest-accepted

#1802 [Add] Added JSitor in online-code-editor database under Frontend category
  database/frontend/online-code-editors.json
Labels: goal: new-link, chore

#1800 chore: add maintainers info with usernames
  CONTRIBUTING.md
  README.md
Labels: chore, 🔒 staff-only

#1809 Fix1806 sidebar responsive
  components/SideNavbar/SideNavbar.tsx
  tailwind.config.js
Labels: bug, priority: medium, hacktoberfest-accepted

#1832 Fix icons sidebar bug
  components/SideNavbar/SideNavbar.tsx
  components/SocialMedia/SocialMediaIconsList.tsx
Labels: bug, hacktoberfest, hacktoberfest-accepted

#1825 Adding link in Icons section
  database/frontend/icons.json
Labels: goal: new-link, chore, priority: low, hacktoberfest, hacktoberfest-accepted

#1823 Add lucide icons link
  database/frontend/icons.json
  pnpm-lock.yaml
Labels: goal: new-link, chore, hacktoberfest, hacktoberfest-accepted

#1814 [ADD] Cybersecurity modules
  components/SideNavbar/SideNavbar.tsx
  components/TopBar/CategoryDescriptions.ts
  components/TopBar/TopBar.tsx
  database/cybersecurity/defensive_security.json
  database/cybersecurity/malware_analysis.json
  database/cybersecurity/offensive_security.json
  database/cybersecurity/web_application_security.json
  database/data.ts
  database/index.ts
  hooks/useFilterDB.ts
  types/index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#1848 add Hugging Face in AI category
  database/artificial_intelligence/artificial-intelligence.json
Labels: chore, goal: new-category

#1849 cp tutorial page fix
  database/competitive_programming/cp-tutorials.json
Labels: bug

#1874 added postman and cypress to testing/backend
  database/backend/testing.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1872 [Add] Flask Project Ideas(#1868)
  database/resources/project-ideas.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1850 Added Codechef to competitive programming
  database/competitive_programming/cp-platforms.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1857 added recipe search API
  database/backend/api.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1865 Adding keycloak
  database/backend/authentication.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted

#1867 added emailProviders as subcategory in backend
  database/backend/email-providers.json
  database/data.ts
  database/index.ts
Labels: goal: new-category, hacktoberfest-accepted, chore

#1858 fixing the spelling mistakes
  CONTRIBUTING.md
  database/frontend/design-inspirations.json
  database/frontend/ui-generators.json
Labels: bug, priority: low, hacktoberfest-accepted

#1839 Add description
  components/TopBar/CategoryDescriptions.ts
Labels: quick-fix

#1862 added technical writing
  .github/ISSUE_TEMPLATE/add_link.yml
Labels: bug, priority: high, hacktoberfest-accepted

#1876 chore: added Brimble
  database/resources/hosting.json
Labels: goal: new-link, priority: low, hacktoberfest, hacktoberfest-accepted, chore

#1734 feat: add mandatory changes
  .github/ISSUE_TEMPLATE/---category-suggestion.yml
  .github/ISSUE_TEMPLATE/add_link.yml
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/category_description.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
  .github/labeler-config.yml
  .github/workflows/greetings.yml
  pages/contributors.tsx
Labels: goal: new-feature

#1875 feat: redirect to the corresponding section based on options in empty page screen
  package.json
  pages/index.tsx
  pnpm-lock.yaml
Labels: priority: low, hacktoberfest, hacktoberfest-accepted, chore

#1881 add: The Tor Project in Open-Source/Projects
  database/open_source/projects.json
Labels: goal: new-link, priority: low, hacktoberfest, hacktoberfest-accepted, chore

#1882 chore: add grammarly in technical writing #1877
  database/technical-writing/tools.json
Labels: goal: new-link, priority: low, hacktoberfest, hacktoberfest-accepted, chore

#1764 [add] Animation: react spring
  database/frontend/animations.json
Labels: hacktoberfest, hacktoberfest-accepted

#1846 feat: Add Women Who Code in the communities category
  database/other/communities.json
Labels: quick-fix, goal: new-category, priority: low, hacktoberfest-accepted

#1891 [DOCS] : Added Social Media icons in README.md
  README.md
Labels: documentation, priority: low, hacktoberfest-accepted

#1895 chore : added C++ and DSA course
  database/languages/cpp.json
Labels: priority: low, chore

#1897 chore: added hoppscotch
  database/backend/testing.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1900 Chore: added technical writing tools
  database/technical-writing/tools.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1899 Update api.json
  database/backend/api.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1840 Auto close menu
  components/SideNavbar/SideNavbarElement.tsx
Labels: goal: new-feature, priority: medium, hacktoberfest-accepted

#1830 fix: revise errors in CODEOWNERS file
  .github/CODEOWNERS
Labels: bug, priority: medium, hacktoberfest-accepted, 🔒 staff-only

#1909 Fix bug
  database/cybersecurity/defensive_security.json
  database/cybersecurity/malware_analysis.json
  database/cybersecurity/offensive_security.json
  database/cybersecurity/web_application_security.json
  database/languages/golang.json
Labels: bug, priority: medium

#1903 Add new Database - mariaDB
  database/backend/database.json
Labels: goal: new-link, priority: low, hacktoberfest, hacktoberfest-accepted

#1717 chore: add Hacktoberfest in Outreach section
  README.md
Labels: documentation, quick-fix, hacktoberfest-accepted

#1922 [Fix] Updating twitter id link
  README.md
Labels: bug, documentation, quick-fix, priority: low, hacktoberfest-accepted

#1914 Chore: Added tutorial link in Competitive Programming Tutorials
  database/competitive_programming/cp-tutorials.json
Labels: goal: new-link, priority: low, hacktoberfest, hacktoberfest-accepted, chore

#1819 add: placement-prep category
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/placement_prep/career-guidance.json
  database/placement_prep/certifications.json
  database/placement_prep/interview-preparation.json
  database/placement_prep/job-portals.json
  database/placement_prep/portfolio-building.json
  database/placement_prep/resume-building.json
  pnpm-lock.yaml
  types/index.ts
Labels: quick-fix, status: ready-to-merge, goal: new-category, hacktoberfest, hacktoberfest-accepted

#1905 add-docker-docs
  database/devops/docker.json
Labels: documentation

#1838 Fixed the behavior of dropdownlist when clicked outside of its scope.
  components/Backdrop/Backdrop.tsx
  components/Cards/Card.tsx
  components/Header/Header.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/popup/popupInfo.tsx
  hooks/useOnClickOutside.ts
  pages/[category]/index.tsx
Labels: bug, priority: medium, hacktoberfest-accepted, goal: bug-fixed

#1916 feat: Add Cyber Security Projects in resources category
  database/resources/project-ideas.json
Labels: goal: new-feature, goal: new-category, priority: low, hacktoberfest-accepted, chore

#1963 Revert "Fixed the behavior of dropdownlist when clicked outside of its scope."
  components/Backdrop/Backdrop.tsx
  components/Cards/Card.tsx
  components/Header/Header.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/popup/popupInfo.tsx
  hooks/useOnClickOutside.ts
  pages/[category]/index.tsx
Labels: bug, priority: medium

#1961 add redux tutorial link
  database/frontend/react.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1952 Added new javascript tutorial link
  database/languages/javascript.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1938 chore: Add Hindi CSS YouTube Playlist (#1935)
  database/youtube/css.json
Labels: priority: low, hacktoberfest-accepted, chore

#1936 added Realtime Colors to Colors/Frontend
  database/frontend/colors.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1928 add css course
  database/youtube/web-development.json
Labels: goal: new-link, priority: low, chore

#1923 Chore : Added a new Typescript course
  database/languages/typescript.json
Labels: priority: low, chore

#1974 Adding Yannickilcher channel in machine learning category
  database/youtube/machine-learning.json
Labels: status: ready-to-merge, goal: new-category, priority: low, chore

#1968 Added CPP playlist to cpp.json
  database/languages/cpp.json
Labels: status: ready-to-merge, priority: low, hacktoberfest, hacktoberfest-accepted

#1965 chore : Added Dsa subcategory under Resources category.
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/resources/dsa.json
Labels: status: ready-to-merge, goal: new-category, priority: low, hacktoberfest-accepted, chore

#1949 add dsa roadmap in category other under roadmaps
  database/other/roadmaps.json
Labels: status: ready-to-merge, goal: new-category, priority: low, chore

#1943 fix: Resource Rendering in the subcategory
  database/data.ts
  database/index.ts
  database/internet_of_things/raspberrypi.json
Labels: bug, status: ready-to-merge, goal: new-category, priority: medium, hacktoberfest-accepted, chore

#1940 Added DSA category
  components/TopBar/CategoryDescriptions.ts
  database/DSA/DSAarticles.json
  database/data.ts
  database/index.ts
  types/index.ts
Labels: status: ready-to-merge, goal: new-category, priority: low, chore

#1932 added a nlp section section
  components/TopBar/CategoryDescriptions.ts
  database/artificial_intelligence/NLP.json
  database/data.ts
  database/index.ts
Labels: goal: new-link, status: ready-to-merge, goal: new-category, priority: low, chore

#1981 feat: Add exercism to CP platform category (#1969)
  database/competitive_programming/cp-platforms.json
Labels: goal: new-feature, status: ready-to-merge, goal: new-category, priority: low, hacktoberfest-accepted, chore

#1980 Add youtube link for complete Kubernetes tutorial issue #1889
  database/data.ts
  database/index.ts
  database/youtube/Kubernetes.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted, chore

#1976 chore: add jenkins subcategory in DevOps
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/devops/jenkins.json
  database/index.ts
Labels: status: ready-to-merge, goal: new-category, priority: low, hacktoberfest-accepted, chore

#1973 Fix Issue #1955: Removed Icon Liberary(Font Awesome) Link from Font c…
  database/frontend/fonts.json
Labels: bug, status: ready-to-merge, priority: low, hacktoberfest-accepted

#1970 UI libraries in fronted added
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/frontend/ui-libraries.json
  database/index.ts
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#1994 Add : System design primer
  database/backend/system-design.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#1988 Add GSAP Animation Library in animation.json
  database/frontend/animations.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted

#1999 feat: add cassandra db to database.json
  database/backend/database.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#1991 chore: replace broken link with new discord icon source
  README.md
Labels: bug, documentation, status: ready-to-merge, priority: low, hacktoberfest-accepted, chore

#1966 chore: add Neetcode in Competitive Programming category
  database/competitive_programming/cp-tutorials.json
Labels: status: ready-to-merge, goal: new-category, priority: low, hacktoberfest-accepted, chore

#2002 chore: add domain category
  database/data.ts
  database/index.ts
  database/other/domains.json
Labels: goal: new-category, priority: low, chore

#1971 Dropdown bug
  components/Backdrop/Backdrop.tsx
  components/Header/Header.tsx
  components/Searchbar/Searchbar.tsx
  components/Searchbar/SearchbarReducer.ts
  components/Searchbar/SearchbarSuggestions.tsx
  components/SideNavbar/SideNavbarBody.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/SideNavbar/SideNavbarElement.tsx
  components/ThemeToggler/themeToggler.tsx
  components/TopBar/TopBar.tsx
  hooks/useOnClickOutside.ts
  layouts/GeneralLayout.tsx
  pages/[category]/[...subcategory].tsx
  pages/index.tsx
Labels: bug, status: ready-to-merge, priority: medium, hacktoberfest-accepted

#2024 fix: laggy navbar transition during theme toggle 🛠️✨
  components/SideNavbar/SideNavbarBody.tsx
Labels: bug, status: ready-to-merge, priority: medium, hacktoberfest-accepted

#2019 Added C++ STL Video Link
  database/languages/cpp.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted, chore

#2016 [Added] Open Source Tutorial Link Added
  database/open_source/os-tutorials.json
Labels: goal: new-link, status: ready-to-merge, priority: low, chore

#2013 chore: add open source projects
  database/open_source/projects.json
Labels: status: ready-to-merge, priority: low, chore

#1950 fix: pagination component overlapping cards #1833
  components/Footer/Footer.tsx
  components/Pagination/Pagination.tsx
Labels: bug, status: ready-to-merge, priority: medium, hacktoberfest-accepted

#2015 add: Free Programming Books to projects open source
  database/open_source/projects.json
Labels: goal: new-link, status: ready-to-merge

#2001 Add PlanetScale Database
  database/backend/database.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2041 Added ThemesBerg to Themes&Templates under Frontend Section
  database/frontend/themes-templates.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2034 added neon db to database.json
  database/backend/database.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2032 Add: New ML Learning resource
  database/youtube/machine-learning.json
Labels: goal: new-link, status: ready-to-merge, hacktoberfest-accepted

#2029 add: zSecurity under cybersecurity category
  database/cybersecurity/offensive_security.json
Labels: goal: new-category, priority: low, chore

#2025 added Chai and Code youtube channel for webdev #hacktoberfest2023
  database/youtube/web-development.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted

#2021 Added solidity as a subcategory
  CONTRIBUTING.md
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/languages/solidity.json
Labels: goal: new-category, priority: low, chore

#1989 Add Accessibility Improvements to Links
  components/SideNavbar/SideNavbarCategory.tsx
  pages/[category]/index.tsx
Labels: status: ready-to-merge, accessibility, priority: medium, hacktoberfest-accepted, chore

#2061 chore:Add new tutorial to open source (#2055)
  database/open_source/os-tutorials.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted, chore

#2045 Added NASA's API in api.json
  database/backend/api.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2056 feat: added the resources for learning git
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/other/git.json
  pnpm-lock.yaml
Labels: goal: new-link, priority: low, hacktoberfest-accepted

#2058 fix: footer layout issue ⚒️✨
  components/BackToTop/BackToTopButton.tsx
  components/Footer/Footer.tsx
  layouts/GeneralLayout.tsx
  pages/[category]/[...subcategory].tsx
  pages/[category]/index.tsx
  pages/index.tsx
  pages/search.tsx
Labels: bug, status: ready-to-merge, priority: medium, hacktoberfest-accepted

#2067 Added frontend course by META
  database/frontend/react.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted

#2060 Added a new resource link in database/youtube/web3-metaverse.json
  database/youtube/web3-metaverse.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted, chore

#1948 feat: add icons next to the "Visit Site" button to signify the destination type
  components/Cards/Card.tsx
  components/popup/popupInfo.tsx
Labels: goal: new-feature, status: ready-to-merge, priority: high, hacktoberfest-accepted

#2092 fix/2085 footer fixed to bottom
  layouts/GeneralLayout.tsx
Labels: bug, status: ready-to-merge, priority: medium

#2072 add: UIColors to Colors under Frontend Section
  database/frontend/colors.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2049 chore:Add new link to c++(#2040)
  database/languages/cpp.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest, hacktoberfest-accepted, chore

#2117 Added <Blockchain roadmap>
  database/other/roadmaps.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2114 feat(add link): Add a new link to Novu in the backend as an email provider
  database/backend/email-providers.json
Labels: goal: new-feature, goal: new-link, status: ready-to-merge, priority: low, priority: high, hacktoberfest-accepted, chore

#2123 feat(add link): Add a new link to Fontspace in the frontend as a fonts provider
  database/frontend/fonts.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2119 docs: fix formatting issues in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: bug, documentation, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2108 Adding Hitesh Sir's YouTube Channel
  database/youtube/web-development.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2066 Added DSA-Courses subcategory in DSA Section
  components/TopBar/CategoryDescriptions.ts
  components/TopBar/TopBar.tsx
  database/data.ts
  database/data_structures/dsa-courses.json
  database/index.ts
Labels: status: ready-to-merge, goal: new-category, priority: low, hacktoberfest-accepted, chore

#2124 chore: nextui added to frontend ui-librariries
  database/frontend/ui-libraries.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#2087 Feat/kubernetes youtube resource
  database/devops/kubernetes.json
  database/youtube/Kubernetes.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2127 feat: add MLH fellowship to open source programs
  database/open_source/os-programs.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2122 Added Python roadmap
  database/other/roadmaps.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#2038 Added a YouTube sub category under DSA category and added a YouTube playlist.
  database/DSA/DSAYouTube.json
Labels: goal: new-category, priority: low, hacktoberfest-accepted, chore

#2120 Update database.json
  database/backend/database.json
Labels: goal: new-link, priority: low, hacktoberfest-accepted, chore

#1953 Remove Unnecessary Description Popup
  components/Header/Header.tsx
  components/TopBar/CategoryDescriptions.ts
  components/TopBar/TopBar.tsx
  components/TopBar/utils.ts
  components/popup/popupCategoryDesc.tsx
  database/data.ts
  database/index.ts
  database/open_source/tutorials.json
  pages/[category]/[...subcategory].tsx
  pages/search.tsx
Labels: status: ready-to-merge, priority: low, hacktoberfest-accepted, chore

#2155 Added DSA youtube playlist - Dataflair
  database/data_structures/dsa-tutorials.json
Labels: goal: new-link, status: ready-to-merge, priority: low, hacktoberfest-accepted

#2146 chore:added striver's 79 dsa cheatsheet
  database/resources/dsa.json
Labels: status: ready-to-merge, priority: low, chore

#2142 Added new course
  database/youtube/web-development.json
Labels: goal: new-link, status: ready-to-merge, hacktoberfest-accepted
