Repository rupali-codes/LinksHub, pull requests merged in 2023-09, with the labels that each got.

#1645 feat: add "Edabit"
  database/frontend/online-code-editors.json
  database/other/other-resources.json
Labels: goal: new-link, chore

#1642 feat: add description of contributors
  components/TopBar/CategoryDescriptions.ts
Labels: goal: new-feature, chore

#1630 feat: Added Roadmaps #1387
  database/data.ts
  database/index.ts
  database/other/roadmaps.json
  types/index.ts
Labels: goal: new-link, chore

#1632 feat: adding chart
  CONTRIBUTING.md
Labels: documentation, level1

#1626 Added Odin Project
  database/frontend/react.json
Labels: goal: new-link, chore

#1643 Top bar distinction feature
  components/Header/Header.tsx
  layouts/GeneralLayout.tsx
  package.json
  pnpm-lock.yaml
Labels: goal: new-feature

#1654 feat: add category in the url
  components/Footer/Footer.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/SideNavbar/SideNavbarElement.tsx
  components/TopBar/TopBar.tsx
  database/artificial_intelligence/artificial-intelligence.json
  database/artificial_intelligence/data-science.json
  database/artificial_intelligence/deep-learning.json
  database/artificial_intelligence/machine-learning.json
  database/cloud_computing_platforms/aws.json
  database/cloud_computing_platforms/azure.json
  database/cloud_computing_platforms/gcp.json
  database/cloud_computing_platforms/ibm.json
  database/cloud_computing_platforms/oracle.json
  database/competitive_programming/cp-platforms.json
  database/competitive_programming/cp-tutorials.json
  database/data.ts
  database/devops/cicd.json
  database/devops/devops-life-cycle.json
  database/devops/devops-methodologies.json
  database/devops/docker.json
  database/devops/kubernetes.json
  database/devops/microservices.json
  database/index.ts
  database/internet_of_things/coursera.json
  database/internet_of_things/raspberry.json
  database/open_source/articles.json
  database/open_source/os-tutorials.json
  database/open_source/projects.json
  database/open_source/tools.json
  pages/[category]/[...subcategory].tsx
  pages/[category]/index.tsx
  tailwind.config.js
  types/index.ts
Labels: goal: new-feature, chore

#1658 fix: Back to top button hoverable even at the top
  components/BackToTop/BackToTopButton.tsx
Labels: bug

#1662 I have added a new link to the machine-learning.json file.
  database/youtube/machine-learning.json
Labels: goal: new-link, chore

#1664 FIX: Card not displaying
  database/data.ts
Labels: bug

#1675 chore: replaced linkshub.vercel.app with linskhub.dev in SECURITY.md
  SECURITY.md
Labels: chore

#1666 [Added] Adding 3D CSS editor to UI Generators sub-category in frontend
  database/frontend/ui-generators.json
Labels: goal: new-link, chore, priority: low

#1650 fix: improve accessibility of scripts
  components/SocialMedia/SocialMediaIconsList.tsx
Labels: bug, chore, accessibility, priority: medium

#1668 chore: Reduce copyright font-size for small screens
  components/Footer/Footer.tsx
Labels: bug, chore, priority: medium

#1681 chore: added setup guidelines in contributing.md file
  CONTRIBUTING.md
  README.md
Labels: documentation, chore

#1682 Fix incorrect alignment of header links
  components/SocialMedia/SocialMediaIconsList.tsx
Labels: bug, chore, priority: medium

#1676 Added Codespaces link in the readme
  README.md
Labels: goal: new-link, chore, priority: low

#1686 Fix/twitter logo
  components/SocialMedia/SocialMediaIconsList.tsx
  package.json
  pnpm-lock.yaml
Labels: bug

#1689 chore: added new resources in multiple categories
  database/backend/system-design.json
  database/backend/testing.json
  database/backend/validation.json
  database/cloud_computing_platforms/aws.json
  database/open_source/projects.json
Labels: chore

#1690 Fixes/description of the subcategory
  components/TopBar/TopBar.tsx
  components/popup/popupInfo.tsx
Labels: bug, chore, goal: new-category

#1696 Update: LinkFree to BioDrop
  database/open_source/projects.json
Labels: goal: new-link, chore

#1660 Adding pagination feature
  components/Footer/Footer.tsx
  components/Pagination/Pagination.tsx
  components/SideNavbar/SideNavbarElement.tsx
  hooks/useLoader 2.ts
  hooks/usePagination.tsx
  layouts/GeneralLayout.tsx
  package.json
  pages/[category]/[...subcategory].tsx
  pages/search.tsx
  pnpm-lock.yaml
Labels: goal: new-feature, chore, collab, priority: high

#1701 add: techncial writing category and Docsify
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/technical-writing/tools.json
  types/index.ts
Labels: documentation, chore, goal: new-category
