Repository rupali-codes/LinksHub, pull requests merged in 2024-01, with the labels that each got.

#2228 chore: added roadmaps.sh in other/roadmaps"
  database/other/roadmaps.json
Labels: priority: low, chore

#2229 feat: Angular - New Subcategory under Frontend
  database/data.ts
  database/frontend/angular.json
  database/index.ts
Labels: goal: new-feature, status: ready-to-merge, goal: new-category, priority: low, priority: high, chore

#2218 feat: add new design for Our Team Section
  components/TopBar/CategoryDescriptions.ts
  data/maintainersData.ts
  database/frontend/ui-libraries.json
  database/resources/official-docs.json
  database/youtube/web-development.json
  layouts/GeneralLayout.tsx
  package.json
  pages/contributors.tsx
  styles/globals.css
Labels: goal: new-feature, in progress, priority: high

#2232 fix copytoclipboard button gap issue #2230
  components/popup/popupInfo.tsx
Labels: bug, status: ready-to-merge, priority: medium

#2226 feat: add searchbar for mobile devices (new design)
  components/Aside/Aside.tsx
  components/MobileBottomNav/MobileBottomNav.tsx
  components/Searchbar/ShortcutKey.tsx
  components/SideNavbar/SideNavbar.tsx
  components/SideNavbar/SideNavbarBody.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  styles/globals.css
Labels: goal: new-feature, priority: high

#2224 Feat: Add new design for search results page(no results found)
  assets/icons/svg/search-icon.svg
  components/Button/Button.tsx
  components/NotFound/NotFound.tsx
  lib/utils.ts
  package.json
  pages/search.tsx
  pnpm-lock.yaml
  tailwind.config.js
Labels: goal: new-design, status: ready-to-merge, priority: high

#2195 Feat: add new design for categories page
  assets/icons/svg/AddIcon.svg
  assets/icons/svg/ArrowIcon.svg
  assets/icons/svg/HomeIcon.svg
  assets/icons/svg/MessageIcon.svg
  components/Breadcrumps/index.tsx
  layouts/GeneralLayout.tsx
  pages/[category]/index.tsx
  styles/globals.css
  tailwind.config.js
Labels: goal: new-design, priority: high

#2211 feat: saved resources page
  components/Sidebar/Sidebar.tsx
  pages/saved.tsx
  public/SaveRemove.png
Labels: goal: new-design, status: ready-to-merge, priority: medium, priority: high

#2220 Changed Home Page UI
  assets/icons/HeartIcon.tsx
  assets/icons/StarIcon.tsx
  assets/icons/svg/starIcon.svg
  components/logo/logo.tsx
  database/index.ts
  layouts/GeneralLayout.tsx
  pages/index.tsx
  tailwind.config.js
Labels: in progress, goal: new-design, priority: high, chore

#2243 feat: update slogan
  README.md
  pages/index.tsx
Labels: goal: new-feature, priority: high

#2239 BUG] Align pagination buttons to bottom
  components/Pagination/Pagination.tsx
  pages/[category]/[...subcategory].tsx
Labels: status: ready-to-merge
