Repository rupali-codes/LinksHub, pull requests merged in 2024-04, with the labels that each got.

#2329 add links to rust on languages/rust
  database/languages/rust.json
Labels: goal: new-link, status: ready-to-merge, priority: low, chore

#2332 ADD email in CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: bug, documentation

#2344 feat: improve styling of various sections for light and dark theme
  components/Breadcrumbs/index.tsx
  components/Cards/Card.tsx
  components/CopyToClipboard/CopyToClipboard.tsx
  components/Footer/Footer.tsx
  components/Searchbar/Searchbar.tsx
  components/TopBar/TopBar.tsx
  components/popup/popupInfo.tsx
  layouts/GeneralLayout.tsx
  pages/[category]/index.tsx
  pages/index.tsx
Labels: goal: new-feature, goal: new-design, priority: high

#2342 Links fixed
  database/cybersecurity/defensive_security.json
Labels: bug, goal: new-link, priority: low, priority: medium, chore

#2318 feat: add icons component and improve codebase structure
  assets/icons/HeartIcon.tsx
  assets/icons/StarIcon.tsx
  assets/icons/svg/AddIcon.svg
  assets/icons/svg/ArrowIcon.svg
  assets/icons/svg/HomeIcon.svg
  assets/icons/svg/MessageIcon.svg
  assets/icons/svg/angle-down.svg
  assets/icons/svg/discord.svg
  assets/icons/svg/github.svg
  assets/icons/svg/heart.svg
  assets/icons/svg/linkedin.svg
  assets/icons/svg/moon.svg
  assets/icons/svg/nav/home-active.svg
  assets/icons/svg/nav/home-inactive.svg
  assets/icons/svg/nav/save-active.svg
  assets/icons/svg/nav/save-inactive.svg
  assets/icons/svg/nav/search-active.svg
  assets/icons/svg/nav/search-inactive.svg
  assets/icons/svg/nav/team-active.svg
  assets/icons/svg/nav/team-inactive.svg
  assets/icons/svg/question-mark.svg
  assets/icons/svg/search-icon.svg
  assets/icons/svg/search.svg
  assets/icons/svg/starIcon.svg
  assets/icons/svg/sun.svg
  assets/icons/svg/x.svg
  assets/logo.svg
  components/Breadcrumbs/index.tsx
  components/Header/Header.tsx
  components/MobileBottomNav/MobileBottomNav.tsx
  components/NotFound/NotFound.tsx
  components/ReportBug/Reportbug.tsx
  components/Searchbar/Searchbar.tsx
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/Sidebar/Sidebar.tsx
  components/ThemeToggler/themeToggler.tsx
  components/TopBar/TopBar.tsx
  components/icons.tsx
  pages/[category]/[...subcategory].tsx
  pages/[category]/index.tsx
  pages/contributors.tsx
  pages/index.tsx
  pages/search.tsx
Labels: goal: new-feature, goal: refactor, priority: high

#2340 Add playwright
  database/backend/testing.json
Labels: status: ready-to-merge

#2347 feat: [ADD]-Sub Category- Automation Tools #2345
  database/data.ts
  database/devops/automation-tools.json
  database/index.ts
Labels: goal: new-feature, status: ready-to-merge, goal: new-category, priority: low, priority: high, chore

#2059 feat: add upvote system
  app/api/route.ts
  components/Cards/Card.tsx
  lib/firebase-admin-config.tsx
  lib/firebase-config.tsx
  package.json
  pnpm-lock.yaml
  public/upvote.png
  public/upvoteFilled.png
  service-account.ts
Labels: goal: new-feature, priority: high
