Repository rupali-codes/LinksHub, pull requests merged in 2024-02, with the labels that each got.

#2245 feat: add Repo-rater GitHub Action
  .github/workflows/repo-rater.yml
Labels: goal: new-feature, priority: high

#2253 [docs] Improve the Support Section
  README.md
Labels: status: ready-to-merge

#2255 chore: add link digitomize in cp/cp-helpers
  components/TopBar/CategoryDescriptions.ts
  database/competitive_programming/cp-helpers.json
  database/data.ts
  database/index.ts
Labels: goal: new-link, priority: low, chore

#2252 #2246 fix search query value in breadcrumbs
  components/Breadcrumps/index.tsx
  components/Searchbar/Searchbar.tsx
  components/TopBar/TopBar.tsx
Labels: bug, status: ready-to-merge, priority: medium

#2264 Add CSS games subcategory under Frontend category.
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/frontend/css-games.json
  database/index.ts
  public/sitemap.xml
Labels: status: ready-to-merge, goal: new-category, priority: low, chore

#2261 To fix #2254 Breadcrumbs issue
  components/Breadcrumbs/index.tsx
  components/TopBar/TopBar.tsx
  pages/[category]/index.tsx
Labels: bug, priority: medium

#2273 Fix: [BUG] Sidebar not scrolling properly
  components/Sidebar/Sidebar.tsx
Labels: bug, priority: medium

#2267 #2262: fix extra space in between Breadcrumb and Content
  layouts/GeneralLayout.tsx
Labels: bug, priority: medium
