Repository rupali-codes/LinksHub, pull requests merged in 2024-12, with the labels that each got.

#2575 feat: add overleaf as a new link under <Technical Writing/Technical Writing Tool>
  database/technical-writing/tools.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2576 feat: add project idx as a new link in frontend / online_code_editors
  database/frontend/online_code_editors.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2583 feat: adding new subcategories to the DevOps category
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/devops/LinksHub.code-workspace
  database/devops/configuration_management.json
  database/devops/containerization_and_orchestration.json
  database/devops/monitoring_and_logging.json
  database/index.ts
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2585 feat: added UI Ball as a new link in frontend / animations
  database/frontend/animations.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2591 feat: add flask as a new link in resources / official-docs
  database/resources/official-docs.json
Labels: documentation, goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2593 feat: Added Nest.js course in Backend category
  components/TopBar/CategoryDescriptions.ts
  database/backend/nest_js.json
  database/data.ts
  database/index.ts
  pages/[category]/[...subcategory].tsx
Labels: goal: new-category, priority: low, chore

#2594 fix: Change search suggestion name 'react' to 'react articles' (#2590)
  database/data.ts
Labels: bug, priority: medium

#2592 fix(sidebar): Resolve issue with main accordion not working (#2567)
  components/SideNavbar/SideNavbarCategory.tsx
Labels: bug, priority: medium

#2597 refactor: updated category names
  .github/ISSUE_TEMPLATE/add_link.yml
Labels: goal: new-category, goal: refactor, priority: low, priority: medium, chore

#2569 chore: added vue js subcategory in frontend category
  database/data.ts
  database/frontend/vuejs.json
  database/index.ts
Labels: goal: new-category, priority: low, chore

#2599 fix: document links fix
  database/ai_tools/chat_bots.json
  database/ai_tools/design.json
  database/frontend/react.json
  database/languages/javascript.json
Labels: bug, priority: medium

#2598 fix: update category description for design tools to 'design_color_to…
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/design/color_tools.json
  database/index.ts
Labels: bug, goal: new-category, priority: low, priority: medium, chore

#2602 fix: improve responsiveness in grid
  pages/contributors.tsx
Labels: bug, priority: medium

#2606 feat: added VueJs desc in CategoryDescriptions.ts
  components/TopBar/CategoryDescriptions.ts
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2608 feat: added claudeAI chatbot link in ai tools / chat_bots
  database/ai_tools/chat_bots.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore
