Repository rupali-codes/LinksHub, pull requests merged in 2024-07, with the labels that each got.

#2395 feat(backend/api): add new Api to Api list (#2364)
  database/backend/api.json
  pnpm-lock.yaml
Labels: goal: new-feature, priority: high

#2417 feat: Added New Resource of Dracula Theme (#2414)
  database/other/devtools.json
Labels: goal: new-feature, priority: high

#2396 Iconse feature added
  database/frontend/icons.json
Labels: goal: new-feature, priority: high

#2415 feat: changes backgound-color at ::selection attribute
  styles/globals.css
Labels: goal: new-feature, priority: high

#2413 Added hover effect on buttons of main page
  pages/index.tsx
Labels: good first issue, chore

#2404 Broken Link Checker - Github Action
  .github/workflows/check_links.yml
  .lycheeignore
Labels: goal: new-link, priority: low, chore

#2432 [Add] TOOOLS.design
  database/ai_tools/design.json
Labels: goal: new-link, chore
