Repository rupali-codes/LinksHub, pull requests merged in 2024-05, with the labels that each got.

#2355 feat: Added Corbado to backend>authentication
  database/backend/authentication.json
Labels: goal: new-feature, priority: high

#2367 chore: revert upvote PR
  app/api/route.ts
  components/Cards/Card.tsx
  lib/firebase-admin-config.tsx
  lib/firebase-config.tsx
  service-account.ts
Labels: priority: low, chore

#2361 Add new subcategory Static Site Generator (SSG)
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/resources/official-docs.json
  database/resources/ssg.json
  pnpm-lock.yaml
  public/sitemap.xml
Labels: goal: new-category, priority: low, chore

#2373 docs: adjusting the step to suggesting new categories
  CONTRIBUTING.md
Labels: documentation, priority: low

#2360 added pulumi iac
  database/devops/iac.json
Labels: goal: new-link, priority: low
