Repository rupali-codes/LinksHub, pull requests merged in 2024-08, with the labels that each got.

#2440 fixes typo in sidebar
  components/SideNavbar/SideNavbarCategory.tsx
Labels: bug, priority: medium

#2427 fix: typos and grammatical errors
  components/Header/Header.tsx
  components/ThemeToggler/themeToggler.tsx
  pages/index.tsx
Labels: bug, priority: medium

#2450 chore(refactor): typo in category page
  pages/[category]/index.tsx
Labels: goal: new-category, goal: refactor, priority: low, priority: medium, chore

#2452 fix: Remove duplicate Tailwind classnames (#2442)
  pages/[category]/index.tsx
  pages/index.tsx
Labels: bug, priority: medium

#2405 feat : Added subcategory chat bots in aitools and added chatgpt in it…
  .github/workflows/check_links.yml
  components/TopBar/CategoryDescriptions.ts
  database/ai_tools/chat_bots.json
  database/data.ts
  database/index.ts
  pages/[category]/[...subcategory].tsx
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2441 [Add] university academy link
  database/youtube/computer_science.json
Labels: goal: new-link, priority: low, chore

#2457 chore(new link): Revising X in Y minutes
  database/youtube/computer_science.json
Labels: goal: new-link, priority: low, chore

#2458 chore: rename package name
  package.json
Labels: priority: low, chore

#2461 chore(new link): add Tech With Tim
  database/languages/python.json
Labels: goal: new-link, priority: low, chore

#2455 Add new resources to learn smart contract development, auditing and security researching.
  database/BlockChain/smart-contracts.json
Labels: goal: new-link, chore

#2460 fix: key prop bug
  components/Header/Header.tsx
Labels: bug, priority: medium

#2464 fix: remove broken links
  CONTRIBUTING.md
  database/ai_tools/design.json
  database/cybersecurity/web_application_security.json
  database/frontend/colors.json
  database/frontend/design_inspiration.json
  database/other/communities.json
  database/resources/blogs.json
  database/resources/e_book.json
  database/youtube/web3_metaverse.json
  database/youtube/web_development.json
Labels: bug, goal: new-link, priority: low, priority: medium, chore, automated-link-issue, broken-link

#2434 chore(typo): rename our team button
  components/Header/Header.tsx
Labels: priority: low, chore

#2433 [Add] Awesome-Design-Tools
  database/frontend/design_inspiration.json
Labels: goal: new-link, priority: low

#2465 resolving conflicts (#2420)
  database/backend/email_providers.json
Labels: goal: new-link, chore

#2466 chore: Add background and border for resource card (#2463)
  components/Cards/Card.tsx
Labels: priority: low, chore

#2467 Fix: Capitalize YouTube correctly in sidebar (#2445)
  components/SideNavbar/SideNavbarCategory.tsx
Labels: bug, priority: medium

#2468 chore(new-link): Indie UI
  database/frontend/ui_libraries.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2473 feat: [ADD] "Design" category and due subcategories
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/design/design_inspiration.json
  database/design/design_tools.json
  database/design/design_tutorials.json
  database/index.ts
  database/youtube/web_development.json
  types/index.ts
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2469 feat: add pull request compliance workflow
  .github/workflows/compliance.yml
Labels: goal: new-feature, priority: high

#2484 chore: Add Click Here link
  database/cybersecurity/malware_analysis.json
Labels: priority: low, chore

#2481 chore: Add Newsletters
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/newsletters/js_Letters.json
  database/newsletters/py_Letters.json
  types/index.ts
Labels: priority: low, chore

#2483 chore: add tech articles
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/tech_articles/react.json
  types/index.ts
Labels: priority: low, chore

#2485 chore: add darknet diaries (2477)
  database/other/podcasts.json
Labels: priority: low, chore
