Repository rupali-codes/LinksHub, pull requests merged in 2024-10, with the labels that each got.

#2513 fix: the Broken link of Language/general_web_fundamental/hitesh choudhary youtube
  database/languages/general_web_fundamentals.json
Labels: bug, goal: new-link, priority: low, priority: medium, chore

#2516 feat: add memfree
  database/artificial_intelligence/artificial_intelligence.json
Labels: goal: new-link, priority: low, chore

#2517 feat: add hubdev
  database/open_source/tools.json
Labels: goal: new-link, chore

#2521 feat: My First PR
  database/open_source/tools.json
Labels: goal: new-feature, priority: high

#2522 feat: add uptime-kuma
  database/other/devtools.json
Labels: goal: new-feature, priority: high

#2527 feat: moves `frontend > colors` to renamed `design > design color tools`
  database/data.ts
  database/design/design_color_tools.json
  database/design/design_tools.json
  database/index.ts
Labels: goal: new-feature, priority: high

#2519 feat(navbar): Created a subcategory Hacktoberfest under open-source c…
  components/SideNavbar/SideNavbarCategory.tsx
  components/SideNavbar/SideNavbarCategoryList.tsx
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/open_source/hacktoberfest.json
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2528 feat: Add a New Card in DevTools category
  database/other/devtools.json
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2540 feat: add Java Category and Subcategory in newsletter and resources added in javascript newsletter
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/newsletters/java_Letters.json
  database/newsletters/js_Letters.json
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2538 feat: add github action to self-assign the issue
  .github/workflows/auto-assign-issues.yml
  CONTRIBUTING.md
Labels: goal: new-feature, priority: high

#2535 chore: Update 'Contribute now' button link
  pages/index.tsx
Labels: goal: new-link, priority: low, chore

#2539 fix: Typo
  database/languages/rust.json
Labels: bug, priority: medium

#2543 chore: fixed text overflown in LinksHub intro columns
  pages/index.tsx
Labels: bug, goal: new-link, priority: low, priority: medium, chore

#2548 chore: added new resource for the css sub-category
  database/languages/css.json
Labels: goal: new-link, priority: low, chore

#2553 feat(resources): Add Anna's Archive link to Resources/E-books
  database/resources/e_book.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore
