Repository rupali-codes/LinksHub, pull requests merged in 2024-03, with the labels that each got.

#2283 Add Dr Link Check
  database/other/devtools.json
Labels: goal: new-link, priority: low, chore

#2272 Change threeJS subcategory name to 3d libraries and add resource links
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/frontend/3d-libraries.json
  database/frontend/three.json
  database/index.ts
Labels: goal: new-link, goal: new-category, priority: low, chore

#2286 chore: Added new resource in javascript
  database/languages/javascript.json
Labels: priority: low, chore

#2285 feat: This commit adds the new subcategory js-chart-libraries to the …
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/frontend/js-chart-libraries.json
  database/index.ts
Labels: goal: new-feature, goal: new-category, priority: low, priority: high, chore

#2280 naukri-link-added
  database/placement_prep/job-portals.json
Labels: goal: new-link, status: ready-to-merge, priority: low, chore

#2269 Fix: [BUG] category name in the breadcrumbs
  components/Breadcrumbs/index.tsx
  components/TopBar/TopBar.tsx
Labels: bug, goal: new-category, priority: low, priority: medium, chore

#2291 Fixed the broken links
  database/cybersecurity/defensive_security.json
  database/cybersecurity/malware_analysis.json
  database/cybersecurity/web_application_security.json
  database/frontend/ui-generators.json
Labels: bug, goal: new-link, priority: low, priority: medium, chore

#2298 freshersworld-added
  database/placement_prep/job-portals.json
Labels: goal: new-link, status: ready-to-merge, 🚀 ready

#2306 Closes #2295 [add] work at a startup link
  database/placement_prep/job-portals.json
Labels: goal: new-link, priority: low, chore

#2311 Closes #2309 Fix favicon
  pages/_document.tsx
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/site.webmanifest
Labels: bug, priority: medium

#2314 Closes #2313 - Spelling Mistakes
  database/backend/testing.json
  database/other/roadmaps.json
  database/placement_prep/job-portals.json
Labels: status: ready-to-merge, 🚀 ready, priority: high

#2305 Closes #2302
  components/Pagination/Pagination.tsx
Labels: status: ready-to-merge, 🚀 ready, priority: medium, goal: bug-fixed

#2300 fix : Handled the async visuals while switching themes in sub-categories pages (#2294)
  layouts/GeneralLayout.tsx
Labels: bug, status: ready-to-merge, 🚀 ready, priority: medium

#2321 Add new JavaScript charting libraries
  database/frontend/js-chart-libraries.json
Labels: status: ready-to-merge

#2320 Add Documentation
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/resources/docs-generator.json
  database/technical-writing/tools.json
  public/sitemap.xml
Labels: goal: new-link, goal: new-category, priority: low
