Repository rupali-codes/LinksHub, pull requests merged in 2025-03, with the labels that each got.

#2647 feat: added meta ai chatbot details in ai tools database
  database/ai_tools/chat_bots.json
Labels: goal: new-feature, priority: high

#2655 chore: added DevOps subcategory in the newsletter category
  components/TopBar/CategoryDescriptions.ts
  database/data.ts
  database/index.ts
  database/newsletters/devops.json
Labels: goal: new-category, priority: low, chore

#2663 feat: Add fountn link (#2641)
  database/design/design_inspiration.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2662 feat: added Grok ai
  database/ai_tools/chat_bots.json
Labels: goal: new-feature, priority: high

#2661 feat: added ChatSutra AI chatbot details
  database/ai_tools/chat_bots.json
Labels: goal: new-feature, priority: high

#2660 feat: Add link
  database/frontend/themes_and_templates.json
Labels: goal: new-feature, goal: new-link, priority: low, priority: high, chore

#2657 feat: added Qwen chatbot details in chat_bots.json
  database/ai_tools/chat_bots.json
Labels: goal: new-feature, priority: high

#2664 chore: add Magic UI library
  database/frontend/ui_libraries.json
Labels: priority: low, chore

#2666 chore: added react bits in frontend
  database/frontend/ui_libraries.json
Labels: goal: new-feature, priority: high

#2669 chore: added Headless UI into UI Library list
  database/frontend/ui_libraries.json
Labels: goal: new-feature, priority: high
